export const studentList = [
  {
    id: 0,
    firstName: "Cédric",
    lastName: "NOYEL",
    email: "cedric.noyel@imt-atlantique.net",
    status: "Absent",
    classGroup: "front",
  },
  {
    id: 1,
    firstName: "Jordan",
    lastName: "GENEVE",
    email: "jodan.geneve@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 2,
    firstName: "Gaël",
    lastName: "BENAISSA",
    email: "gael.benaissa@imt-atlantique.net",
    status: "Absent",
    classGroup: "front",
  },
  {
    id: 3,
    firstName: "Mathis",
    lastName: "DELAUNAY",
    email: "mathis.delaunay@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 4,
    firstName: "Léa",
    lastName: "LOUESDON",
    email: "lea.louesdon@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 5,
    firstName: "Chloé",
    lastName: "MASONI",
    email: "chloe.masoni@imt-atlantique.net",
    status: "En cours",
    classGroup: "front",
  },
  {
    id: 6,
    firstName: "Gaëtan",
    lastName: "CEUTERICKX",
    status: "En télétravail",
    email: "gaetan.CEUTERICKX@imt-atlantique.net",
    classGroup: "front",
  },
  {
    id: 7,
    firstName: "Océane",
    lastName: "BERTHE",
    status: "En cours",
    email: "oceane.BERTHE@imt-atlantique.net",
    classGroup: "front",
  },
  {
    id: 8,
    firstName: "Lucille",
    lastName: "GILLARD",
    status: "En cours",
    email: "Lucille.GILLARD@imt-atlantique.net",
    classGroup: "front",
  },
  {
    id: 9,
    firstName: "Axel",
    lastName: "COUDRAY",
    status: "En cours",
    email: "Axel.COUDRAY@imt-atlantique.net",
    classGroup: "front",
  },
  {
    id: 10,
    firstName: "Xavier",
    lastName: "ALEMAN",
    status: "En cours",
    email: "Xavier.ALEMAN@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 11,
    firstName: "Paul",
    lastName: "BAVAZZANO",
    status: "En cours",
    email: "Paul.BAVAZZANO@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 12,
    firstName: "Robin",
    lastName: "CARREZ",
    status: "En cours",
    email: "Robin.CARREZ@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 13,
    firstName: "Emeric",
    lastName: "CHONIGBAUM",
    status: "En cours",
    email: "Emeric.CHONIGBAUM@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 14,
    firstName: "Théo",
    lastName: "COUTAN",
    status: "En cours",
    email: "Theo.COUTAN@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 15,
    firstName: "Evrard-Nil",
    lastName: "DAILLET",
    status: "En cours",
    email: "evrard-nil.DAILLET@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 16,
    firstName: "Ismaël",
    lastName: "ELKANTACH",
    status: "En cours",
    email: "ismael.ELKANTACH@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 17,
    firstName: "Maël",
    lastName: "GAONACH",
    status: "En cours",
    email: "mael.GAONACH@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 18,
    firstName: "Raphaël",
    lastName: "HASCOUET",
    status: "En cours",
    email: "raphael.HASCOUET@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 19,
    firstName: "Thomas",
    lastName: "HERBELIN",
    status: "Absent",
    email: "Thomas.HERBELIN@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 20,
    firstName: "Marc",
    lastName: "LAMY",
    status: "En cours",
    email: "marc.lamy@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 21,
    firstName: "Simon",
    lastName: "LEBARS",
    status: "En cours",
    email: "simon.lebars@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 22,
    firstName: "Samy",
    lastName: "LEGALLOUDEC",
    status: "En cours",
    email: "samy.LEGALLOUDEC@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 23,
    firstName: "Florian",
    lastName: "LEMENN",
    status: "En cours",
    email: "Florian.LEMENN@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 24,
    firstName: "Antoine",
    lastName: "OMOND",
    status: "En cours",
    email: "Antoine.OMOND@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 25,
    firstName: "Lucas",
    lastName: "PELEC",
    status: "En cours",
    email: "Lucas.PELEC@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 26,
    firstName: "Javed",
    lastName: "SYEDKHASIM",
    status: "En cours",
    email: "Javed.SYEDKHASIM@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 27,
    firstName: "Barthélémy",
    lastName: "TEK",
    status: "En cours",
    email: "barthelemy.tek@imt-atlantique.net",
    classGroup: "back",
  },
  {
    id: 28,
    firstName: "Hoan-My",
    lastName: "Tran",
    status: "En cours",
    email: "hoan-my.tran@imt-atlantique.net",
    classGroup: "back",
  },
];
